/*
Cortex XSOAR API

This is the public REST API to integrate with the Cortex XSOAR server. HTTP request can be sent using any HTTP-client.  For an example dedicated client take a look at: https://github.com/demisto/demisto-py.  Requests must include API-key that can be generated in the Cortex XSOAR web client under 'Settings' -> 'Integrations' -> 'API keys'   Optimistic Locking and Versioning\\:  When using Cortex XSOAR REST API, you will need to make sure to work on the latest version of the item (incident, entry, etc.), otherwise, you will get a DB version error (which not allow you to override a newer item). In addition, you can pass 'version\\: -1' to force data override (make sure that other users data might be lost).  Assume that Alice and Bob both read the same data from Cortex XSOAR server, then they both changed the data, and then both tried to write the new versions back to the server. Whose changes should be saved? Alice’s? Bob’s? To solve this, each data item in Cortex XSOAR has a numeric incremental version. If Alice saved an item with version 4 and Bob trying to save the same item with version 3, Cortex XSOAR will rollback Bob request and returns a DB version conflict error. Bob will need to get the latest item and work on it so Alice work will not get lost.  Example request using 'curl'\\:  ``` curl 'https://hostname:443/incidents/search' -H 'content-type: application/json' -H 'accept: application/json' -H 'Authorization: <API Key goes here>' --data-binary '{\"filter\":{\"query\":\"-status:closed -category:job\",\"period\":{\"by\":\"day\",\"fromValue\":7}}}' --compressed ```

API version: 2.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"encoding/json"
)

// UpdateResponse struct for UpdateResponse
type UpdateResponse struct {
	NotUpdated *int64    `json:"notUpdated,omitempty"`
	UpdatedIds *[]string `json:"updatedIds,omitempty"`
}

// NewUpdateResponse instantiates a new UpdateResponse object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewUpdateResponse() *UpdateResponse {
	this := UpdateResponse{}
	return &this
}

// NewUpdateResponseWithDefaults instantiates a new UpdateResponse object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewUpdateResponseWithDefaults() *UpdateResponse {
	this := UpdateResponse{}
	return &this
}

// GetNotUpdated returns the NotUpdated field value if set, zero value otherwise.
func (o *UpdateResponse) GetNotUpdated() int64 {
	if o == nil || o.NotUpdated == nil {
		var ret int64
		return ret
	}
	return *o.NotUpdated
}

// GetNotUpdatedOk returns a tuple with the NotUpdated field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *UpdateResponse) GetNotUpdatedOk() (*int64, bool) {
	if o == nil || o.NotUpdated == nil {
		return nil, false
	}
	return o.NotUpdated, true
}

// HasNotUpdated returns a boolean if a field has been set.
func (o *UpdateResponse) HasNotUpdated() bool {
	if o != nil && o.NotUpdated != nil {
		return true
	}

	return false
}

// SetNotUpdated gets a reference to the given int64 and assigns it to the NotUpdated field.
func (o *UpdateResponse) SetNotUpdated(v int64) {
	o.NotUpdated = &v
}

// GetUpdatedIds returns the UpdatedIds field value if set, zero value otherwise.
func (o *UpdateResponse) GetUpdatedIds() []string {
	if o == nil || o.UpdatedIds == nil {
		var ret []string
		return ret
	}
	return *o.UpdatedIds
}

// GetUpdatedIdsOk returns a tuple with the UpdatedIds field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *UpdateResponse) GetUpdatedIdsOk() (*[]string, bool) {
	if o == nil || o.UpdatedIds == nil {
		return nil, false
	}
	return o.UpdatedIds, true
}

// HasUpdatedIds returns a boolean if a field has been set.
func (o *UpdateResponse) HasUpdatedIds() bool {
	if o != nil && o.UpdatedIds != nil {
		return true
	}

	return false
}

// SetUpdatedIds gets a reference to the given []string and assigns it to the UpdatedIds field.
func (o *UpdateResponse) SetUpdatedIds(v []string) {
	o.UpdatedIds = &v
}

func (o UpdateResponse) MarshalJSON() ([]byte, error) {
	toSerialize := map[string]interface{}{}
	if o.NotUpdated != nil {
		toSerialize["notUpdated"] = o.NotUpdated
	}
	if o.UpdatedIds != nil {
		toSerialize["updatedIds"] = o.UpdatedIds
	}
	return json.Marshal(toSerialize)
}

type NullableUpdateResponse struct {
	value *UpdateResponse
	isSet bool
}

func (v NullableUpdateResponse) Get() *UpdateResponse {
	return v.value
}

func (v *NullableUpdateResponse) Set(val *UpdateResponse) {
	v.value = val
	v.isSet = true
}

func (v NullableUpdateResponse) IsSet() bool {
	return v.isSet
}

func (v *NullableUpdateResponse) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableUpdateResponse(val *UpdateResponse) *NullableUpdateResponse {
	return &NullableUpdateResponse{value: val, isSet: true}
}

func (v NullableUpdateResponse) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableUpdateResponse) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
