/*
Cortex XSOAR API

This is the public REST API to integrate with the Cortex XSOAR server. HTTP request can be sent using any HTTP-client.  For an example dedicated client take a look at: https://github.com/demisto/demisto-py.  Requests must include API-key that can be generated in the Cortex XSOAR web client under 'Settings' -> 'Integrations' -> 'API keys'   Optimistic Locking and Versioning\\:  When using Cortex XSOAR REST API, you will need to make sure to work on the latest version of the item (incident, entry, etc.), otherwise, you will get a DB version error (which not allow you to override a newer item). In addition, you can pass 'version\\: -1' to force data override (make sure that other users data might be lost).  Assume that Alice and Bob both read the same data from Cortex XSOAR server, then they both changed the data, and then both tried to write the new versions back to the server. Whose changes should be saved? Alice’s? Bob’s? To solve this, each data item in Cortex XSOAR has a numeric incremental version. If Alice saved an item with version 4 and Bob trying to save the same item with version 3, Cortex XSOAR will rollback Bob request and returns a DB version conflict error. Bob will need to get the latest item and work on it so Alice work will not get lost.  Example request using 'curl'\\:  ``` curl 'https://hostname:443/incidents/search' -H 'content-type: application/json' -H 'accept: application/json' -H 'Authorization: <API Key goes here>' --data-binary '{\"filter\":{\"query\":\"-status:closed -category:job\",\"period\":{\"by\":\"day\",\"fromValue\":7}}}' --compressed ```

API version: 2.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"encoding/json"
)

// TagsFieldValues struct for TagsFieldValues
type TagsFieldValues struct {
	Data *[]string `json:"data,omitempty"`
}

// NewTagsFieldValues instantiates a new TagsFieldValues object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewTagsFieldValues() *TagsFieldValues {
	this := TagsFieldValues{}
	return &this
}

// NewTagsFieldValuesWithDefaults instantiates a new TagsFieldValues object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewTagsFieldValuesWithDefaults() *TagsFieldValues {
	this := TagsFieldValues{}
	return &this
}

// GetData returns the Data field value if set, zero value otherwise.
func (o *TagsFieldValues) GetData() []string {
	if o == nil || o.Data == nil {
		var ret []string
		return ret
	}
	return *o.Data
}

// GetDataOk returns a tuple with the Data field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *TagsFieldValues) GetDataOk() (*[]string, bool) {
	if o == nil || o.Data == nil {
		return nil, false
	}
	return o.Data, true
}

// HasData returns a boolean if a field has been set.
func (o *TagsFieldValues) HasData() bool {
	if o != nil && o.Data != nil {
		return true
	}

	return false
}

// SetData gets a reference to the given []string and assigns it to the Data field.
func (o *TagsFieldValues) SetData(v []string) {
	o.Data = &v
}

func (o TagsFieldValues) MarshalJSON() ([]byte, error) {
	toSerialize := map[string]interface{}{}
	if o.Data != nil {
		toSerialize["data"] = o.Data
	}
	return json.Marshal(toSerialize)
}

type NullableTagsFieldValues struct {
	value *TagsFieldValues
	isSet bool
}

func (v NullableTagsFieldValues) Get() *TagsFieldValues {
	return v.value
}

func (v *NullableTagsFieldValues) Set(val *TagsFieldValues) {
	v.value = val
	v.isSet = true
}

func (v NullableTagsFieldValues) IsSet() bool {
	return v.isSet
}

func (v *NullableTagsFieldValues) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableTagsFieldValues(val *TagsFieldValues) *NullableTagsFieldValues {
	return &NullableTagsFieldValues{value: val, isSet: true}
}

func (v NullableTagsFieldValues) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableTagsFieldValues) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
