/*
Cortex XSOAR API

This is the public REST API to integrate with the Cortex XSOAR server. HTTP request can be sent using any HTTP-client.  For an example dedicated client take a look at: https://github.com/demisto/demisto-py.  Requests must include API-key that can be generated in the Cortex XSOAR web client under 'Settings' -> 'Integrations' -> 'API keys'   Optimistic Locking and Versioning\\:  When using Cortex XSOAR REST API, you will need to make sure to work on the latest version of the item (incident, entry, etc.), otherwise, you will get a DB version error (which not allow you to override a newer item). In addition, you can pass 'version\\: -1' to force data override (make sure that other users data might be lost).  Assume that Alice and Bob both read the same data from Cortex XSOAR server, then they both changed the data, and then both tried to write the new versions back to the server. Whose changes should be saved? Alice’s? Bob’s? To solve this, each data item in Cortex XSOAR has a numeric incremental version. If Alice saved an item with version 4 and Bob trying to save the same item with version 3, Cortex XSOAR will rollback Bob request and returns a DB version conflict error. Bob will need to get the latest item and work on it so Alice work will not get lost.  Example request using 'curl'\\:  ``` curl 'https://hostname:443/incidents/search' -H 'content-type: application/json' -H 'accept: application/json' -H 'Authorization: <API Key goes here>' --data-binary '{\"filter\":{\"query\":\"-status:closed -category:job\",\"period\":{\"by\":\"day\",\"fromValue\":7}}}' --compressed ```

API version: 2.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"encoding/json"
)

// EntryTask EntryTask holds information regarding the related task
type EntryTask struct {
	PlaybookName *string `json:"playbookName,omitempty"`
	Quiet        *bool   `json:"quiet,omitempty"`
	TaskId       *string `json:"taskId,omitempty"`
	TaskName     *string `json:"taskName,omitempty"`
	TaskStatus   *string `json:"taskStatus,omitempty"`
}

// NewEntryTask instantiates a new EntryTask object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewEntryTask() *EntryTask {
	this := EntryTask{}
	return &this
}

// NewEntryTaskWithDefaults instantiates a new EntryTask object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewEntryTaskWithDefaults() *EntryTask {
	this := EntryTask{}
	return &this
}

// GetPlaybookName returns the PlaybookName field value if set, zero value otherwise.
func (o *EntryTask) GetPlaybookName() string {
	if o == nil || o.PlaybookName == nil {
		var ret string
		return ret
	}
	return *o.PlaybookName
}

// GetPlaybookNameOk returns a tuple with the PlaybookName field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *EntryTask) GetPlaybookNameOk() (*string, bool) {
	if o == nil || o.PlaybookName == nil {
		return nil, false
	}
	return o.PlaybookName, true
}

// HasPlaybookName returns a boolean if a field has been set.
func (o *EntryTask) HasPlaybookName() bool {
	if o != nil && o.PlaybookName != nil {
		return true
	}

	return false
}

// SetPlaybookName gets a reference to the given string and assigns it to the PlaybookName field.
func (o *EntryTask) SetPlaybookName(v string) {
	o.PlaybookName = &v
}

// GetQuiet returns the Quiet field value if set, zero value otherwise.
func (o *EntryTask) GetQuiet() bool {
	if o == nil || o.Quiet == nil {
		var ret bool
		return ret
	}
	return *o.Quiet
}

// GetQuietOk returns a tuple with the Quiet field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *EntryTask) GetQuietOk() (*bool, bool) {
	if o == nil || o.Quiet == nil {
		return nil, false
	}
	return o.Quiet, true
}

// HasQuiet returns a boolean if a field has been set.
func (o *EntryTask) HasQuiet() bool {
	if o != nil && o.Quiet != nil {
		return true
	}

	return false
}

// SetQuiet gets a reference to the given bool and assigns it to the Quiet field.
func (o *EntryTask) SetQuiet(v bool) {
	o.Quiet = &v
}

// GetTaskId returns the TaskId field value if set, zero value otherwise.
func (o *EntryTask) GetTaskId() string {
	if o == nil || o.TaskId == nil {
		var ret string
		return ret
	}
	return *o.TaskId
}

// GetTaskIdOk returns a tuple with the TaskId field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *EntryTask) GetTaskIdOk() (*string, bool) {
	if o == nil || o.TaskId == nil {
		return nil, false
	}
	return o.TaskId, true
}

// HasTaskId returns a boolean if a field has been set.
func (o *EntryTask) HasTaskId() bool {
	if o != nil && o.TaskId != nil {
		return true
	}

	return false
}

// SetTaskId gets a reference to the given string and assigns it to the TaskId field.
func (o *EntryTask) SetTaskId(v string) {
	o.TaskId = &v
}

// GetTaskName returns the TaskName field value if set, zero value otherwise.
func (o *EntryTask) GetTaskName() string {
	if o == nil || o.TaskName == nil {
		var ret string
		return ret
	}
	return *o.TaskName
}

// GetTaskNameOk returns a tuple with the TaskName field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *EntryTask) GetTaskNameOk() (*string, bool) {
	if o == nil || o.TaskName == nil {
		return nil, false
	}
	return o.TaskName, true
}

// HasTaskName returns a boolean if a field has been set.
func (o *EntryTask) HasTaskName() bool {
	if o != nil && o.TaskName != nil {
		return true
	}

	return false
}

// SetTaskName gets a reference to the given string and assigns it to the TaskName field.
func (o *EntryTask) SetTaskName(v string) {
	o.TaskName = &v
}

// GetTaskStatus returns the TaskStatus field value if set, zero value otherwise.
func (o *EntryTask) GetTaskStatus() string {
	if o == nil || o.TaskStatus == nil {
		var ret string
		return ret
	}
	return *o.TaskStatus
}

// GetTaskStatusOk returns a tuple with the TaskStatus field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *EntryTask) GetTaskStatusOk() (*string, bool) {
	if o == nil || o.TaskStatus == nil {
		return nil, false
	}
	return o.TaskStatus, true
}

// HasTaskStatus returns a boolean if a field has been set.
func (o *EntryTask) HasTaskStatus() bool {
	if o != nil && o.TaskStatus != nil {
		return true
	}

	return false
}

// SetTaskStatus gets a reference to the given string and assigns it to the TaskStatus field.
func (o *EntryTask) SetTaskStatus(v string) {
	o.TaskStatus = &v
}

func (o EntryTask) MarshalJSON() ([]byte, error) {
	toSerialize := map[string]interface{}{}
	if o.PlaybookName != nil {
		toSerialize["playbookName"] = o.PlaybookName
	}
	if o.Quiet != nil {
		toSerialize["quiet"] = o.Quiet
	}
	if o.TaskId != nil {
		toSerialize["taskId"] = o.TaskId
	}
	if o.TaskName != nil {
		toSerialize["taskName"] = o.TaskName
	}
	if o.TaskStatus != nil {
		toSerialize["taskStatus"] = o.TaskStatus
	}
	return json.Marshal(toSerialize)
}

type NullableEntryTask struct {
	value *EntryTask
	isSet bool
}

func (v NullableEntryTask) Get() *EntryTask {
	return v.value
}

func (v *NullableEntryTask) Set(val *EntryTask) {
	v.value = val
	v.isSet = true
}

func (v NullableEntryTask) IsSet() bool {
	return v.isSet
}

func (v *NullableEntryTask) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableEntryTask(val *EntryTask) *NullableEntryTask {
	return &NullableEntryTask{value: val, isSet: true}
}

func (v NullableEntryTask) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableEntryTask) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
