/*
Cortex XSOAR API

This is the public REST API to integrate with the Cortex XSOAR server. HTTP request can be sent using any HTTP-client.  For an example dedicated client take a look at: https://github.com/demisto/demisto-py.  Requests must include API-key that can be generated in the Cortex XSOAR web client under 'Settings' -> 'Integrations' -> 'API keys'   Optimistic Locking and Versioning\\:  When using Cortex XSOAR REST API, you will need to make sure to work on the latest version of the item (incident, entry, etc.), otherwise, you will get a DB version error (which not allow you to override a newer item). In addition, you can pass 'version\\: -1' to force data override (make sure that other users data might be lost).  Assume that Alice and Bob both read the same data from Cortex XSOAR server, then they both changed the data, and then both tried to write the new versions back to the server. Whose changes should be saved? Alice’s? Bob’s? To solve this, each data item in Cortex XSOAR has a numeric incremental version. If Alice saved an item with version 4 and Bob trying to save the same item with version 3, Cortex XSOAR will rollback Bob request and returns a DB version conflict error. Bob will need to get the latest item and work on it so Alice work will not get lost.  Example request using 'curl'\\:  ``` curl 'https://hostname:443/incidents/search' -H 'content-type: application/json' -H 'accept: application/json' -H 'Authorization: <API Key goes here>' --data-binary '{\"filter\":{\"query\":\"-status:closed -category:job\",\"period\":{\"by\":\"day\",\"fromValue\":7}}}' --compressed ```

API version: 2.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"encoding/json"
)

// RelationshipAPI struct for RelationshipAPI
type RelationshipAPI struct {
	Brand         *string       `json:"brand,omitempty"`
	EntityA       *string       `json:"entityA,omitempty"`
	EntityAFamily *string       `json:"entityAFamily,omitempty"`
	EntityAType   *string       `json:"entityAType,omitempty"`
	EntityB       *string       `json:"entityB,omitempty"`
	EntityBFamily *string       `json:"entityBFamily,omitempty"`
	EntityBType   *string       `json:"entityBType,omitempty"`
	Fields        *CustomFields `json:"fields,omitempty"`
	Id            *string       `json:"id,omitempty"`
	Instance      *string       `json:"instance,omitempty"`
	Name          *string       `json:"name,omitempty"`
	Reliability   *string       `json:"reliability,omitempty"`
	ReverseName   *string       `json:"reverseName,omitempty"`
	Type          *string       `json:"type,omitempty"`
}

// NewRelationshipAPI instantiates a new RelationshipAPI object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewRelationshipAPI() *RelationshipAPI {
	this := RelationshipAPI{}
	return &this
}

// NewRelationshipAPIWithDefaults instantiates a new RelationshipAPI object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewRelationshipAPIWithDefaults() *RelationshipAPI {
	this := RelationshipAPI{}
	return &this
}

// GetBrand returns the Brand field value if set, zero value otherwise.
func (o *RelationshipAPI) GetBrand() string {
	if o == nil || o.Brand == nil {
		var ret string
		return ret
	}
	return *o.Brand
}

// GetBrandOk returns a tuple with the Brand field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *RelationshipAPI) GetBrandOk() (*string, bool) {
	if o == nil || o.Brand == nil {
		return nil, false
	}
	return o.Brand, true
}

// HasBrand returns a boolean if a field has been set.
func (o *RelationshipAPI) HasBrand() bool {
	if o != nil && o.Brand != nil {
		return true
	}

	return false
}

// SetBrand gets a reference to the given string and assigns it to the Brand field.
func (o *RelationshipAPI) SetBrand(v string) {
	o.Brand = &v
}

// GetEntityA returns the EntityA field value if set, zero value otherwise.
func (o *RelationshipAPI) GetEntityA() string {
	if o == nil || o.EntityA == nil {
		var ret string
		return ret
	}
	return *o.EntityA
}

// GetEntityAOk returns a tuple with the EntityA field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *RelationshipAPI) GetEntityAOk() (*string, bool) {
	if o == nil || o.EntityA == nil {
		return nil, false
	}
	return o.EntityA, true
}

// HasEntityA returns a boolean if a field has been set.
func (o *RelationshipAPI) HasEntityA() bool {
	if o != nil && o.EntityA != nil {
		return true
	}

	return false
}

// SetEntityA gets a reference to the given string and assigns it to the EntityA field.
func (o *RelationshipAPI) SetEntityA(v string) {
	o.EntityA = &v
}

// GetEntityAFamily returns the EntityAFamily field value if set, zero value otherwise.
func (o *RelationshipAPI) GetEntityAFamily() string {
	if o == nil || o.EntityAFamily == nil {
		var ret string
		return ret
	}
	return *o.EntityAFamily
}

// GetEntityAFamilyOk returns a tuple with the EntityAFamily field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *RelationshipAPI) GetEntityAFamilyOk() (*string, bool) {
	if o == nil || o.EntityAFamily == nil {
		return nil, false
	}
	return o.EntityAFamily, true
}

// HasEntityAFamily returns a boolean if a field has been set.
func (o *RelationshipAPI) HasEntityAFamily() bool {
	if o != nil && o.EntityAFamily != nil {
		return true
	}

	return false
}

// SetEntityAFamily gets a reference to the given string and assigns it to the EntityAFamily field.
func (o *RelationshipAPI) SetEntityAFamily(v string) {
	o.EntityAFamily = &v
}

// GetEntityAType returns the EntityAType field value if set, zero value otherwise.
func (o *RelationshipAPI) GetEntityAType() string {
	if o == nil || o.EntityAType == nil {
		var ret string
		return ret
	}
	return *o.EntityAType
}

// GetEntityATypeOk returns a tuple with the EntityAType field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *RelationshipAPI) GetEntityATypeOk() (*string, bool) {
	if o == nil || o.EntityAType == nil {
		return nil, false
	}
	return o.EntityAType, true
}

// HasEntityAType returns a boolean if a field has been set.
func (o *RelationshipAPI) HasEntityAType() bool {
	if o != nil && o.EntityAType != nil {
		return true
	}

	return false
}

// SetEntityAType gets a reference to the given string and assigns it to the EntityAType field.
func (o *RelationshipAPI) SetEntityAType(v string) {
	o.EntityAType = &v
}

// GetEntityB returns the EntityB field value if set, zero value otherwise.
func (o *RelationshipAPI) GetEntityB() string {
	if o == nil || o.EntityB == nil {
		var ret string
		return ret
	}
	return *o.EntityB
}

// GetEntityBOk returns a tuple with the EntityB field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *RelationshipAPI) GetEntityBOk() (*string, bool) {
	if o == nil || o.EntityB == nil {
		return nil, false
	}
	return o.EntityB, true
}

// HasEntityB returns a boolean if a field has been set.
func (o *RelationshipAPI) HasEntityB() bool {
	if o != nil && o.EntityB != nil {
		return true
	}

	return false
}

// SetEntityB gets a reference to the given string and assigns it to the EntityB field.
func (o *RelationshipAPI) SetEntityB(v string) {
	o.EntityB = &v
}

// GetEntityBFamily returns the EntityBFamily field value if set, zero value otherwise.
func (o *RelationshipAPI) GetEntityBFamily() string {
	if o == nil || o.EntityBFamily == nil {
		var ret string
		return ret
	}
	return *o.EntityBFamily
}

// GetEntityBFamilyOk returns a tuple with the EntityBFamily field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *RelationshipAPI) GetEntityBFamilyOk() (*string, bool) {
	if o == nil || o.EntityBFamily == nil {
		return nil, false
	}
	return o.EntityBFamily, true
}

// HasEntityBFamily returns a boolean if a field has been set.
func (o *RelationshipAPI) HasEntityBFamily() bool {
	if o != nil && o.EntityBFamily != nil {
		return true
	}

	return false
}

// SetEntityBFamily gets a reference to the given string and assigns it to the EntityBFamily field.
func (o *RelationshipAPI) SetEntityBFamily(v string) {
	o.EntityBFamily = &v
}

// GetEntityBType returns the EntityBType field value if set, zero value otherwise.
func (o *RelationshipAPI) GetEntityBType() string {
	if o == nil || o.EntityBType == nil {
		var ret string
		return ret
	}
	return *o.EntityBType
}

// GetEntityBTypeOk returns a tuple with the EntityBType field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *RelationshipAPI) GetEntityBTypeOk() (*string, bool) {
	if o == nil || o.EntityBType == nil {
		return nil, false
	}
	return o.EntityBType, true
}

// HasEntityBType returns a boolean if a field has been set.
func (o *RelationshipAPI) HasEntityBType() bool {
	if o != nil && o.EntityBType != nil {
		return true
	}

	return false
}

// SetEntityBType gets a reference to the given string and assigns it to the EntityBType field.
func (o *RelationshipAPI) SetEntityBType(v string) {
	o.EntityBType = &v
}

// GetFields returns the Fields field value if set, zero value otherwise.
func (o *RelationshipAPI) GetFields() CustomFields {
	if o == nil || o.Fields == nil {
		var ret CustomFields
		return ret
	}
	return *o.Fields
}

// GetFieldsOk returns a tuple with the Fields field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *RelationshipAPI) GetFieldsOk() (*CustomFields, bool) {
	if o == nil || o.Fields == nil {
		return nil, false
	}
	return o.Fields, true
}

// HasFields returns a boolean if a field has been set.
func (o *RelationshipAPI) HasFields() bool {
	if o != nil && o.Fields != nil {
		return true
	}

	return false
}

// SetFields gets a reference to the given CustomFields and assigns it to the Fields field.
func (o *RelationshipAPI) SetFields(v CustomFields) {
	o.Fields = &v
}

// GetId returns the Id field value if set, zero value otherwise.
func (o *RelationshipAPI) GetId() string {
	if o == nil || o.Id == nil {
		var ret string
		return ret
	}
	return *o.Id
}

// GetIdOk returns a tuple with the Id field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *RelationshipAPI) GetIdOk() (*string, bool) {
	if o == nil || o.Id == nil {
		return nil, false
	}
	return o.Id, true
}

// HasId returns a boolean if a field has been set.
func (o *RelationshipAPI) HasId() bool {
	if o != nil && o.Id != nil {
		return true
	}

	return false
}

// SetId gets a reference to the given string and assigns it to the Id field.
func (o *RelationshipAPI) SetId(v string) {
	o.Id = &v
}

// GetInstance returns the Instance field value if set, zero value otherwise.
func (o *RelationshipAPI) GetInstance() string {
	if o == nil || o.Instance == nil {
		var ret string
		return ret
	}
	return *o.Instance
}

// GetInstanceOk returns a tuple with the Instance field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *RelationshipAPI) GetInstanceOk() (*string, bool) {
	if o == nil || o.Instance == nil {
		return nil, false
	}
	return o.Instance, true
}

// HasInstance returns a boolean if a field has been set.
func (o *RelationshipAPI) HasInstance() bool {
	if o != nil && o.Instance != nil {
		return true
	}

	return false
}

// SetInstance gets a reference to the given string and assigns it to the Instance field.
func (o *RelationshipAPI) SetInstance(v string) {
	o.Instance = &v
}

// GetName returns the Name field value if set, zero value otherwise.
func (o *RelationshipAPI) GetName() string {
	if o == nil || o.Name == nil {
		var ret string
		return ret
	}
	return *o.Name
}

// GetNameOk returns a tuple with the Name field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *RelationshipAPI) GetNameOk() (*string, bool) {
	if o == nil || o.Name == nil {
		return nil, false
	}
	return o.Name, true
}

// HasName returns a boolean if a field has been set.
func (o *RelationshipAPI) HasName() bool {
	if o != nil && o.Name != nil {
		return true
	}

	return false
}

// SetName gets a reference to the given string and assigns it to the Name field.
func (o *RelationshipAPI) SetName(v string) {
	o.Name = &v
}

// GetReliability returns the Reliability field value if set, zero value otherwise.
func (o *RelationshipAPI) GetReliability() string {
	if o == nil || o.Reliability == nil {
		var ret string
		return ret
	}
	return *o.Reliability
}

// GetReliabilityOk returns a tuple with the Reliability field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *RelationshipAPI) GetReliabilityOk() (*string, bool) {
	if o == nil || o.Reliability == nil {
		return nil, false
	}
	return o.Reliability, true
}

// HasReliability returns a boolean if a field has been set.
func (o *RelationshipAPI) HasReliability() bool {
	if o != nil && o.Reliability != nil {
		return true
	}

	return false
}

// SetReliability gets a reference to the given string and assigns it to the Reliability field.
func (o *RelationshipAPI) SetReliability(v string) {
	o.Reliability = &v
}

// GetReverseName returns the ReverseName field value if set, zero value otherwise.
func (o *RelationshipAPI) GetReverseName() string {
	if o == nil || o.ReverseName == nil {
		var ret string
		return ret
	}
	return *o.ReverseName
}

// GetReverseNameOk returns a tuple with the ReverseName field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *RelationshipAPI) GetReverseNameOk() (*string, bool) {
	if o == nil || o.ReverseName == nil {
		return nil, false
	}
	return o.ReverseName, true
}

// HasReverseName returns a boolean if a field has been set.
func (o *RelationshipAPI) HasReverseName() bool {
	if o != nil && o.ReverseName != nil {
		return true
	}

	return false
}

// SetReverseName gets a reference to the given string and assigns it to the ReverseName field.
func (o *RelationshipAPI) SetReverseName(v string) {
	o.ReverseName = &v
}

// GetType returns the Type field value if set, zero value otherwise.
func (o *RelationshipAPI) GetType() string {
	if o == nil || o.Type == nil {
		var ret string
		return ret
	}
	return *o.Type
}

// GetTypeOk returns a tuple with the Type field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *RelationshipAPI) GetTypeOk() (*string, bool) {
	if o == nil || o.Type == nil {
		return nil, false
	}
	return o.Type, true
}

// HasType returns a boolean if a field has been set.
func (o *RelationshipAPI) HasType() bool {
	if o != nil && o.Type != nil {
		return true
	}

	return false
}

// SetType gets a reference to the given string and assigns it to the Type field.
func (o *RelationshipAPI) SetType(v string) {
	o.Type = &v
}

func (o RelationshipAPI) MarshalJSON() ([]byte, error) {
	toSerialize := map[string]interface{}{}
	if o.Brand != nil {
		toSerialize["brand"] = o.Brand
	}
	if o.EntityA != nil {
		toSerialize["entityA"] = o.EntityA
	}
	if o.EntityAFamily != nil {
		toSerialize["entityAFamily"] = o.EntityAFamily
	}
	if o.EntityAType != nil {
		toSerialize["entityAType"] = o.EntityAType
	}
	if o.EntityB != nil {
		toSerialize["entityB"] = o.EntityB
	}
	if o.EntityBFamily != nil {
		toSerialize["entityBFamily"] = o.EntityBFamily
	}
	if o.EntityBType != nil {
		toSerialize["entityBType"] = o.EntityBType
	}
	if o.Fields != nil {
		toSerialize["fields"] = o.Fields
	}
	if o.Id != nil {
		toSerialize["id"] = o.Id
	}
	if o.Instance != nil {
		toSerialize["instance"] = o.Instance
	}
	if o.Name != nil {
		toSerialize["name"] = o.Name
	}
	if o.Reliability != nil {
		toSerialize["reliability"] = o.Reliability
	}
	if o.ReverseName != nil {
		toSerialize["reverseName"] = o.ReverseName
	}
	if o.Type != nil {
		toSerialize["type"] = o.Type
	}
	return json.Marshal(toSerialize)
}

type NullableRelationshipAPI struct {
	value *RelationshipAPI
	isSet bool
}

func (v NullableRelationshipAPI) Get() *RelationshipAPI {
	return v.value
}

func (v *NullableRelationshipAPI) Set(val *RelationshipAPI) {
	v.value = val
	v.isSet = true
}

func (v NullableRelationshipAPI) IsSet() bool {
	return v.isSet
}

func (v *NullableRelationshipAPI) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableRelationshipAPI(val *RelationshipAPI) *NullableRelationshipAPI {
	return &NullableRelationshipAPI{value: val, isSet: true}
}

func (v NullableRelationshipAPI) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableRelationshipAPI) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
