/*
Cortex XSOAR API

This is the public REST API to integrate with the Cortex XSOAR server. HTTP request can be sent using any HTTP-client.  For an example dedicated client take a look at: https://github.com/demisto/demisto-py.  Requests must include API-key that can be generated in the Cortex XSOAR web client under 'Settings' -> 'Integrations' -> 'API keys'   Optimistic Locking and Versioning\\:  When using Cortex XSOAR REST API, you will need to make sure to work on the latest version of the item (incident, entry, etc.), otherwise, you will get a DB version error (which not allow you to override a newer item). In addition, you can pass 'version\\: -1' to force data override (make sure that other users data might be lost).  Assume that Alice and Bob both read the same data from Cortex XSOAR server, then they both changed the data, and then both tried to write the new versions back to the server. Whose changes should be saved? Alice’s? Bob’s? To solve this, each data item in Cortex XSOAR has a numeric incremental version. If Alice saved an item with version 4 and Bob trying to save the same item with version 3, Cortex XSOAR will rollback Bob request and returns a DB version conflict error. Bob will need to get the latest item and work on it so Alice work will not get lost.  Example request using 'curl'\\:  ``` curl 'https://hostname:443/incidents/search' -H 'content-type: application/json' -H 'accept: application/json' -H 'Authorization: <API Key goes here>' --data-binary '{\"filter\":{\"query\":\"-status:closed -category:job\",\"period\":{\"by\":\"day\",\"fromValue\":7}}}' --compressed ```

API version: 2.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"encoding/json"
)

// ReportAutomation struct for ReportAutomation
type ReportAutomation struct {
	// ModuleArgs represents module args
	Args    *map[string]map[string]interface{} `json:"args,omitempty"`
	Id      *string                            `json:"id,omitempty"`
	Name    *string                            `json:"name,omitempty"`
	NoEvent *bool                              `json:"noEvent,omitempty"`
}

// NewReportAutomation instantiates a new ReportAutomation object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewReportAutomation() *ReportAutomation {
	this := ReportAutomation{}
	return &this
}

// NewReportAutomationWithDefaults instantiates a new ReportAutomation object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewReportAutomationWithDefaults() *ReportAutomation {
	this := ReportAutomation{}
	return &this
}

// GetArgs returns the Args field value if set, zero value otherwise.
func (o *ReportAutomation) GetArgs() map[string]map[string]interface{} {
	if o == nil || o.Args == nil {
		var ret map[string]map[string]interface{}
		return ret
	}
	return *o.Args
}

// GetArgsOk returns a tuple with the Args field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ReportAutomation) GetArgsOk() (*map[string]map[string]interface{}, bool) {
	if o == nil || o.Args == nil {
		return nil, false
	}
	return o.Args, true
}

// HasArgs returns a boolean if a field has been set.
func (o *ReportAutomation) HasArgs() bool {
	if o != nil && o.Args != nil {
		return true
	}

	return false
}

// SetArgs gets a reference to the given map[string]map[string]interface{} and assigns it to the Args field.
func (o *ReportAutomation) SetArgs(v map[string]map[string]interface{}) {
	o.Args = &v
}

// GetId returns the Id field value if set, zero value otherwise.
func (o *ReportAutomation) GetId() string {
	if o == nil || o.Id == nil {
		var ret string
		return ret
	}
	return *o.Id
}

// GetIdOk returns a tuple with the Id field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ReportAutomation) GetIdOk() (*string, bool) {
	if o == nil || o.Id == nil {
		return nil, false
	}
	return o.Id, true
}

// HasId returns a boolean if a field has been set.
func (o *ReportAutomation) HasId() bool {
	if o != nil && o.Id != nil {
		return true
	}

	return false
}

// SetId gets a reference to the given string and assigns it to the Id field.
func (o *ReportAutomation) SetId(v string) {
	o.Id = &v
}

// GetName returns the Name field value if set, zero value otherwise.
func (o *ReportAutomation) GetName() string {
	if o == nil || o.Name == nil {
		var ret string
		return ret
	}
	return *o.Name
}

// GetNameOk returns a tuple with the Name field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ReportAutomation) GetNameOk() (*string, bool) {
	if o == nil || o.Name == nil {
		return nil, false
	}
	return o.Name, true
}

// HasName returns a boolean if a field has been set.
func (o *ReportAutomation) HasName() bool {
	if o != nil && o.Name != nil {
		return true
	}

	return false
}

// SetName gets a reference to the given string and assigns it to the Name field.
func (o *ReportAutomation) SetName(v string) {
	o.Name = &v
}

// GetNoEvent returns the NoEvent field value if set, zero value otherwise.
func (o *ReportAutomation) GetNoEvent() bool {
	if o == nil || o.NoEvent == nil {
		var ret bool
		return ret
	}
	return *o.NoEvent
}

// GetNoEventOk returns a tuple with the NoEvent field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ReportAutomation) GetNoEventOk() (*bool, bool) {
	if o == nil || o.NoEvent == nil {
		return nil, false
	}
	return o.NoEvent, true
}

// HasNoEvent returns a boolean if a field has been set.
func (o *ReportAutomation) HasNoEvent() bool {
	if o != nil && o.NoEvent != nil {
		return true
	}

	return false
}

// SetNoEvent gets a reference to the given bool and assigns it to the NoEvent field.
func (o *ReportAutomation) SetNoEvent(v bool) {
	o.NoEvent = &v
}

func (o ReportAutomation) MarshalJSON() ([]byte, error) {
	toSerialize := map[string]interface{}{}
	if o.Args != nil {
		toSerialize["args"] = o.Args
	}
	if o.Id != nil {
		toSerialize["id"] = o.Id
	}
	if o.Name != nil {
		toSerialize["name"] = o.Name
	}
	if o.NoEvent != nil {
		toSerialize["noEvent"] = o.NoEvent
	}
	return json.Marshal(toSerialize)
}

type NullableReportAutomation struct {
	value *ReportAutomation
	isSet bool
}

func (v NullableReportAutomation) Get() *ReportAutomation {
	return v.value
}

func (v *NullableReportAutomation) Set(val *ReportAutomation) {
	v.value = val
	v.isSet = true
}

func (v NullableReportAutomation) IsSet() bool {
	return v.isSet
}

func (v *NullableReportAutomation) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableReportAutomation(val *ReportAutomation) *NullableReportAutomation {
	return &NullableReportAutomation{value: val, isSet: true}
}

func (v NullableReportAutomation) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableReportAutomation) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
