/*
Cortex XSOAR API

This is the public REST API to integrate with the Cortex XSOAR server. HTTP request can be sent using any HTTP-client.  For an example dedicated client take a look at: https://github.com/demisto/demisto-py.  Requests must include API-key that can be generated in the Cortex XSOAR web client under 'Settings' -> 'Integrations' -> 'API keys'   Optimistic Locking and Versioning\\:  When using Cortex XSOAR REST API, you will need to make sure to work on the latest version of the item (incident, entry, etc.), otherwise, you will get a DB version error (which not allow you to override a newer item). In addition, you can pass 'version\\: -1' to force data override (make sure that other users data might be lost).  Assume that Alice and Bob both read the same data from Cortex XSOAR server, then they both changed the data, and then both tried to write the new versions back to the server. Whose changes should be saved? Alice’s? Bob’s? To solve this, each data item in Cortex XSOAR has a numeric incremental version. If Alice saved an item with version 4 and Bob trying to save the same item with version 3, Cortex XSOAR will rollback Bob request and returns a DB version conflict error. Bob will need to get the latest item and work on it so Alice work will not get lost.  Example request using 'curl'\\:  ``` curl 'https://hostname:443/incidents/search' -H 'content-type: application/json' -H 'accept: application/json' -H 'Authorization: <API Key goes here>' --data-binary '{\"filter\":{\"query\":\"-status:closed -category:job\",\"period\":{\"by\":\"day\",\"fromValue\":7}}}' --compressed ```

API version: 2.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"encoding/json"
)

// QueryState QueryState represents the playbook query state
type QueryState struct {
	BatchSize    *int64    `json:"batchSize,omitempty"`
	CurrentPage  *int64    `json:"currentPage,omitempty"`
	SearchAfter  *[]string `json:"searchAfter,omitempty"`
	TotalResults *int64    `json:"totalResults,omitempty"`
}

// NewQueryState instantiates a new QueryState object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewQueryState() *QueryState {
	this := QueryState{}
	return &this
}

// NewQueryStateWithDefaults instantiates a new QueryState object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewQueryStateWithDefaults() *QueryState {
	this := QueryState{}
	return &this
}

// GetBatchSize returns the BatchSize field value if set, zero value otherwise.
func (o *QueryState) GetBatchSize() int64 {
	if o == nil || o.BatchSize == nil {
		var ret int64
		return ret
	}
	return *o.BatchSize
}

// GetBatchSizeOk returns a tuple with the BatchSize field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *QueryState) GetBatchSizeOk() (*int64, bool) {
	if o == nil || o.BatchSize == nil {
		return nil, false
	}
	return o.BatchSize, true
}

// HasBatchSize returns a boolean if a field has been set.
func (o *QueryState) HasBatchSize() bool {
	if o != nil && o.BatchSize != nil {
		return true
	}

	return false
}

// SetBatchSize gets a reference to the given int64 and assigns it to the BatchSize field.
func (o *QueryState) SetBatchSize(v int64) {
	o.BatchSize = &v
}

// GetCurrentPage returns the CurrentPage field value if set, zero value otherwise.
func (o *QueryState) GetCurrentPage() int64 {
	if o == nil || o.CurrentPage == nil {
		var ret int64
		return ret
	}
	return *o.CurrentPage
}

// GetCurrentPageOk returns a tuple with the CurrentPage field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *QueryState) GetCurrentPageOk() (*int64, bool) {
	if o == nil || o.CurrentPage == nil {
		return nil, false
	}
	return o.CurrentPage, true
}

// HasCurrentPage returns a boolean if a field has been set.
func (o *QueryState) HasCurrentPage() bool {
	if o != nil && o.CurrentPage != nil {
		return true
	}

	return false
}

// SetCurrentPage gets a reference to the given int64 and assigns it to the CurrentPage field.
func (o *QueryState) SetCurrentPage(v int64) {
	o.CurrentPage = &v
}

// GetSearchAfter returns the SearchAfter field value if set, zero value otherwise.
func (o *QueryState) GetSearchAfter() []string {
	if o == nil || o.SearchAfter == nil {
		var ret []string
		return ret
	}
	return *o.SearchAfter
}

// GetSearchAfterOk returns a tuple with the SearchAfter field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *QueryState) GetSearchAfterOk() (*[]string, bool) {
	if o == nil || o.SearchAfter == nil {
		return nil, false
	}
	return o.SearchAfter, true
}

// HasSearchAfter returns a boolean if a field has been set.
func (o *QueryState) HasSearchAfter() bool {
	if o != nil && o.SearchAfter != nil {
		return true
	}

	return false
}

// SetSearchAfter gets a reference to the given []string and assigns it to the SearchAfter field.
func (o *QueryState) SetSearchAfter(v []string) {
	o.SearchAfter = &v
}

// GetTotalResults returns the TotalResults field value if set, zero value otherwise.
func (o *QueryState) GetTotalResults() int64 {
	if o == nil || o.TotalResults == nil {
		var ret int64
		return ret
	}
	return *o.TotalResults
}

// GetTotalResultsOk returns a tuple with the TotalResults field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *QueryState) GetTotalResultsOk() (*int64, bool) {
	if o == nil || o.TotalResults == nil {
		return nil, false
	}
	return o.TotalResults, true
}

// HasTotalResults returns a boolean if a field has been set.
func (o *QueryState) HasTotalResults() bool {
	if o != nil && o.TotalResults != nil {
		return true
	}

	return false
}

// SetTotalResults gets a reference to the given int64 and assigns it to the TotalResults field.
func (o *QueryState) SetTotalResults(v int64) {
	o.TotalResults = &v
}

func (o QueryState) MarshalJSON() ([]byte, error) {
	toSerialize := map[string]interface{}{}
	if o.BatchSize != nil {
		toSerialize["batchSize"] = o.BatchSize
	}
	if o.CurrentPage != nil {
		toSerialize["currentPage"] = o.CurrentPage
	}
	if o.SearchAfter != nil {
		toSerialize["searchAfter"] = o.SearchAfter
	}
	if o.TotalResults != nil {
		toSerialize["totalResults"] = o.TotalResults
	}
	return json.Marshal(toSerialize)
}

type NullableQueryState struct {
	value *QueryState
	isSet bool
}

func (v NullableQueryState) Get() *QueryState {
	return v.value
}

func (v *NullableQueryState) Set(val *QueryState) {
	v.value = val
	v.isSet = true
}

func (v NullableQueryState) IsSet() bool {
	return v.isSet
}

func (v *NullableQueryState) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableQueryState(val *QueryState) *NullableQueryState {
	return &NullableQueryState{value: val, isSet: true}
}

func (v NullableQueryState) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableQueryState) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
