/*
Cortex XSOAR API

This is the public REST API to integrate with the Cortex XSOAR server. HTTP request can be sent using any HTTP-client.  For an example dedicated client take a look at: https://github.com/demisto/demisto-py.  Requests must include API-key that can be generated in the Cortex XSOAR web client under 'Settings' -> 'Integrations' -> 'API keys'   Optimistic Locking and Versioning\\:  When using Cortex XSOAR REST API, you will need to make sure to work on the latest version of the item (incident, entry, etc.), otherwise, you will get a DB version error (which not allow you to override a newer item). In addition, you can pass 'version\\: -1' to force data override (make sure that other users data might be lost).  Assume that Alice and Bob both read the same data from Cortex XSOAR server, then they both changed the data, and then both tried to write the new versions back to the server. Whose changes should be saved? Alice’s? Bob’s? To solve this, each data item in Cortex XSOAR has a numeric incremental version. If Alice saved an item with version 4 and Bob trying to save the same item with version 3, Cortex XSOAR will rollback Bob request and returns a DB version conflict error. Bob will need to get the latest item and work on it so Alice work will not get lost.  Example request using 'curl'\\:  ``` curl 'https://hostname:443/incidents/search' -H 'content-type: application/json' -H 'accept: application/json' -H 'Authorization: <API Key goes here>' --data-binary '{\"filter\":{\"query\":\"-status:closed -category:job\",\"period\":{\"by\":\"day\",\"fromValue\":7}}}' --compressed ```

API version: 2.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"encoding/json"
)

// DockerImage DockerImage details
type DockerImage struct {
	CreatedAt    *string `json:"createdAt,omitempty"`
	CreatedSince *string `json:"createdSince,omitempty"`
	Id           *string `json:"id,omitempty"`
	Repository   *string `json:"repository,omitempty"`
	Size         *string `json:"size,omitempty"`
	Tag          *string `json:"tag,omitempty"`
}

// NewDockerImage instantiates a new DockerImage object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewDockerImage() *DockerImage {
	this := DockerImage{}
	return &this
}

// NewDockerImageWithDefaults instantiates a new DockerImage object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewDockerImageWithDefaults() *DockerImage {
	this := DockerImage{}
	return &this
}

// GetCreatedAt returns the CreatedAt field value if set, zero value otherwise.
func (o *DockerImage) GetCreatedAt() string {
	if o == nil || o.CreatedAt == nil {
		var ret string
		return ret
	}
	return *o.CreatedAt
}

// GetCreatedAtOk returns a tuple with the CreatedAt field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *DockerImage) GetCreatedAtOk() (*string, bool) {
	if o == nil || o.CreatedAt == nil {
		return nil, false
	}
	return o.CreatedAt, true
}

// HasCreatedAt returns a boolean if a field has been set.
func (o *DockerImage) HasCreatedAt() bool {
	if o != nil && o.CreatedAt != nil {
		return true
	}

	return false
}

// SetCreatedAt gets a reference to the given string and assigns it to the CreatedAt field.
func (o *DockerImage) SetCreatedAt(v string) {
	o.CreatedAt = &v
}

// GetCreatedSince returns the CreatedSince field value if set, zero value otherwise.
func (o *DockerImage) GetCreatedSince() string {
	if o == nil || o.CreatedSince == nil {
		var ret string
		return ret
	}
	return *o.CreatedSince
}

// GetCreatedSinceOk returns a tuple with the CreatedSince field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *DockerImage) GetCreatedSinceOk() (*string, bool) {
	if o == nil || o.CreatedSince == nil {
		return nil, false
	}
	return o.CreatedSince, true
}

// HasCreatedSince returns a boolean if a field has been set.
func (o *DockerImage) HasCreatedSince() bool {
	if o != nil && o.CreatedSince != nil {
		return true
	}

	return false
}

// SetCreatedSince gets a reference to the given string and assigns it to the CreatedSince field.
func (o *DockerImage) SetCreatedSince(v string) {
	o.CreatedSince = &v
}

// GetId returns the Id field value if set, zero value otherwise.
func (o *DockerImage) GetId() string {
	if o == nil || o.Id == nil {
		var ret string
		return ret
	}
	return *o.Id
}

// GetIdOk returns a tuple with the Id field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *DockerImage) GetIdOk() (*string, bool) {
	if o == nil || o.Id == nil {
		return nil, false
	}
	return o.Id, true
}

// HasId returns a boolean if a field has been set.
func (o *DockerImage) HasId() bool {
	if o != nil && o.Id != nil {
		return true
	}

	return false
}

// SetId gets a reference to the given string and assigns it to the Id field.
func (o *DockerImage) SetId(v string) {
	o.Id = &v
}

// GetRepository returns the Repository field value if set, zero value otherwise.
func (o *DockerImage) GetRepository() string {
	if o == nil || o.Repository == nil {
		var ret string
		return ret
	}
	return *o.Repository
}

// GetRepositoryOk returns a tuple with the Repository field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *DockerImage) GetRepositoryOk() (*string, bool) {
	if o == nil || o.Repository == nil {
		return nil, false
	}
	return o.Repository, true
}

// HasRepository returns a boolean if a field has been set.
func (o *DockerImage) HasRepository() bool {
	if o != nil && o.Repository != nil {
		return true
	}

	return false
}

// SetRepository gets a reference to the given string and assigns it to the Repository field.
func (o *DockerImage) SetRepository(v string) {
	o.Repository = &v
}

// GetSize returns the Size field value if set, zero value otherwise.
func (o *DockerImage) GetSize() string {
	if o == nil || o.Size == nil {
		var ret string
		return ret
	}
	return *o.Size
}

// GetSizeOk returns a tuple with the Size field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *DockerImage) GetSizeOk() (*string, bool) {
	if o == nil || o.Size == nil {
		return nil, false
	}
	return o.Size, true
}

// HasSize returns a boolean if a field has been set.
func (o *DockerImage) HasSize() bool {
	if o != nil && o.Size != nil {
		return true
	}

	return false
}

// SetSize gets a reference to the given string and assigns it to the Size field.
func (o *DockerImage) SetSize(v string) {
	o.Size = &v
}

// GetTag returns the Tag field value if set, zero value otherwise.
func (o *DockerImage) GetTag() string {
	if o == nil || o.Tag == nil {
		var ret string
		return ret
	}
	return *o.Tag
}

// GetTagOk returns a tuple with the Tag field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *DockerImage) GetTagOk() (*string, bool) {
	if o == nil || o.Tag == nil {
		return nil, false
	}
	return o.Tag, true
}

// HasTag returns a boolean if a field has been set.
func (o *DockerImage) HasTag() bool {
	if o != nil && o.Tag != nil {
		return true
	}

	return false
}

// SetTag gets a reference to the given string and assigns it to the Tag field.
func (o *DockerImage) SetTag(v string) {
	o.Tag = &v
}

func (o DockerImage) MarshalJSON() ([]byte, error) {
	toSerialize := map[string]interface{}{}
	if o.CreatedAt != nil {
		toSerialize["createdAt"] = o.CreatedAt
	}
	if o.CreatedSince != nil {
		toSerialize["createdSince"] = o.CreatedSince
	}
	if o.Id != nil {
		toSerialize["id"] = o.Id
	}
	if o.Repository != nil {
		toSerialize["repository"] = o.Repository
	}
	if o.Size != nil {
		toSerialize["size"] = o.Size
	}
	if o.Tag != nil {
		toSerialize["tag"] = o.Tag
	}
	return json.Marshal(toSerialize)
}

type NullableDockerImage struct {
	value *DockerImage
	isSet bool
}

func (v NullableDockerImage) Get() *DockerImage {
	return v.value
}

func (v *NullableDockerImage) Set(val *DockerImage) {
	v.value = val
	v.isSet = true
}

func (v NullableDockerImage) IsSet() bool {
	return v.isSet
}

func (v *NullableDockerImage) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableDockerImage(val *DockerImage) *NullableDockerImage {
	return &NullableDockerImage{value: val, isSet: true}
}

func (v NullableDockerImage) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableDockerImage) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
