/*
Cortex XSOAR API

This is the public REST API to integrate with the Cortex XSOAR server. HTTP request can be sent using any HTTP-client.  For an example dedicated client take a look at: https://github.com/demisto/demisto-py.  Requests must include API-key that can be generated in the Cortex XSOAR web client under 'Settings' -> 'Integrations' -> 'API keys'   Optimistic Locking and Versioning\\:  When using Cortex XSOAR REST API, you will need to make sure to work on the latest version of the item (incident, entry, etc.), otherwise, you will get a DB version error (which not allow you to override a newer item). In addition, you can pass 'version\\: -1' to force data override (make sure that other users data might be lost).  Assume that Alice and Bob both read the same data from Cortex XSOAR server, then they both changed the data, and then both tried to write the new versions back to the server. Whose changes should be saved? Alice’s? Bob’s? To solve this, each data item in Cortex XSOAR has a numeric incremental version. If Alice saved an item with version 4 and Bob trying to save the same item with version 3, Cortex XSOAR will rollback Bob request and returns a DB version conflict error. Bob will need to get the latest item and work on it so Alice work will not get lost.  Example request using 'curl'\\:  ``` curl 'https://hostname:443/incidents/search' -H 'content-type: application/json' -H 'accept: application/json' -H 'Authorization: <API Key goes here>' --data-binary '{\"filter\":{\"query\":\"-status:closed -category:job\",\"period\":{\"by\":\"day\",\"fromValue\":7}}}' --compressed ```

API version: 2.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"encoding/json"
)

// LayoutAPI LayoutAPI - request sent from the client contains some or all of the fields.
type LayoutAPI struct {
	Kind   *string `json:"kind,omitempty"`
	Layout *Layout `json:"layout,omitempty"`
	TypeId *string `json:"typeId,omitempty"`
}

// NewLayoutAPI instantiates a new LayoutAPI object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewLayoutAPI() *LayoutAPI {
	this := LayoutAPI{}
	return &this
}

// NewLayoutAPIWithDefaults instantiates a new LayoutAPI object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewLayoutAPIWithDefaults() *LayoutAPI {
	this := LayoutAPI{}
	return &this
}

// GetKind returns the Kind field value if set, zero value otherwise.
func (o *LayoutAPI) GetKind() string {
	if o == nil || o.Kind == nil {
		var ret string
		return ret
	}
	return *o.Kind
}

// GetKindOk returns a tuple with the Kind field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *LayoutAPI) GetKindOk() (*string, bool) {
	if o == nil || o.Kind == nil {
		return nil, false
	}
	return o.Kind, true
}

// HasKind returns a boolean if a field has been set.
func (o *LayoutAPI) HasKind() bool {
	if o != nil && o.Kind != nil {
		return true
	}

	return false
}

// SetKind gets a reference to the given string and assigns it to the Kind field.
func (o *LayoutAPI) SetKind(v string) {
	o.Kind = &v
}

// GetLayout returns the Layout field value if set, zero value otherwise.
func (o *LayoutAPI) GetLayout() Layout {
	if o == nil || o.Layout == nil {
		var ret Layout
		return ret
	}
	return *o.Layout
}

// GetLayoutOk returns a tuple with the Layout field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *LayoutAPI) GetLayoutOk() (*Layout, bool) {
	if o == nil || o.Layout == nil {
		return nil, false
	}
	return o.Layout, true
}

// HasLayout returns a boolean if a field has been set.
func (o *LayoutAPI) HasLayout() bool {
	if o != nil && o.Layout != nil {
		return true
	}

	return false
}

// SetLayout gets a reference to the given Layout and assigns it to the Layout field.
func (o *LayoutAPI) SetLayout(v Layout) {
	o.Layout = &v
}

// GetTypeId returns the TypeId field value if set, zero value otherwise.
func (o *LayoutAPI) GetTypeId() string {
	if o == nil || o.TypeId == nil {
		var ret string
		return ret
	}
	return *o.TypeId
}

// GetTypeIdOk returns a tuple with the TypeId field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *LayoutAPI) GetTypeIdOk() (*string, bool) {
	if o == nil || o.TypeId == nil {
		return nil, false
	}
	return o.TypeId, true
}

// HasTypeId returns a boolean if a field has been set.
func (o *LayoutAPI) HasTypeId() bool {
	if o != nil && o.TypeId != nil {
		return true
	}

	return false
}

// SetTypeId gets a reference to the given string and assigns it to the TypeId field.
func (o *LayoutAPI) SetTypeId(v string) {
	o.TypeId = &v
}

func (o LayoutAPI) MarshalJSON() ([]byte, error) {
	toSerialize := map[string]interface{}{}
	if o.Kind != nil {
		toSerialize["kind"] = o.Kind
	}
	if o.Layout != nil {
		toSerialize["layout"] = o.Layout
	}
	if o.TypeId != nil {
		toSerialize["typeId"] = o.TypeId
	}
	return json.Marshal(toSerialize)
}

type NullableLayoutAPI struct {
	value *LayoutAPI
	isSet bool
}

func (v NullableLayoutAPI) Get() *LayoutAPI {
	return v.value
}

func (v *NullableLayoutAPI) Set(val *LayoutAPI) {
	v.value = val
	v.isSet = true
}

func (v NullableLayoutAPI) IsSet() bool {
	return v.isSet
}

func (v *NullableLayoutAPI) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableLayoutAPI(val *LayoutAPI) *NullableLayoutAPI {
	return &NullableLayoutAPI{value: val, isSet: true}
}

func (v NullableLayoutAPI) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableLayoutAPI) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
